freebsd_instance:
  image_family: freebsd-12-2

task:
  name: vlang
  script:
    - pkg install -y git-lite
    - cd /root
    - "[ -d dist ] || git clone https://github.com/vlang/v"
    - cd v
    - make
    - ./v symlink

task:
  name: check
  script:
    - v fmt -c .
    - v vet -W .

task:
  name: build
  script:
    - mkdir -p dist/usr/local/bin
    - v -prod -o dist/usr/local/bin/runj .

task:
  name: pkg
  script:
    - pkg create -M dist/manifest -p dist/plist -r dist -o dist -v
